### ISSUE TITLE
!Doctype being remove

### ISSUE THREAD

**Issue by peteringram0** [jackfranklin/html-dist#22] opened 2016-09-21 16:41 UTC
@jackfranklin 

The doctype is being removed on output files, i can see that this looks intensional from the readme, why is this please? Would i be possible to add this as an option within the config? 

Thanks,

**Comment by jackfranklin** [comment] 2016-09-22 07:31
This is a dupe of #20 so I'll close this in favour of that one.

This isn't intentional, it just never crossed my mind! It's a bug that needs fixing.

**Closed as completed by jackfranklin** 2016-09-22 07:31 UTC
